backend:
  name: git-gateway
  branch: main
  repo: threenine/paybolt-docs
publish_mode: editorial_workflow
site_url: https://paybolt.dev
logo_url: https://threenine.co.uk/images/threenine_tag.png
display_url: https://paybolt.dev
show_preview_links: true
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: threenine-co-uk
    api_key: 896994212468486
collections:
    - name: "documentation"
      identifier_field: title
      label: "Documentation"
      folder: "content/docs"
      format: 'frontmatter'
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: true}
          - { label: "Description", name: "description", widget: "string", required: true}
          - { label: "Category",
              name: "category",
              widget: "select",
              options: ["Introduction", "Guides", "Reference", "Troubleshooting"],
              required: true
          }
          - { label: "Summary" , name: "summary", widget: "text" }
          - {label: "Body", name: "body", widget: "markdown" }
